var price1 = 5;
var price2 =8.5;
var name = 'al amin';
var yes = true;
var dummy;
console.log(typeof price1);
console.log(typeof price2);
console.log(typeof name);
console.log(typeof yes);
console.log(typeof dummy);